#ifndef BOARD_H
#define BOARD_H

#include "at32f403a_407.h"
#include <delay_systick.h>
#include "audio_codec.h"

#define SYSTICK_MULTIPLIER 11

#define LED_PIN GPIO_PINS_13
#define LED_PORT GPIOC
#define LED_CLOCK CRM_GPIOC_PERIPH_CLOCK

#define TLV_RESET_CLOCK CRM_GPIOB_PERIPH_CLOCK
#define TLV_RESET_PORT GPIOB
#define TLV_RESET_PIN GPIO_PINS_7

#define LED_OFF LED_PORT->scr = LED_PIN
#define LED_ON LED_PORT->clr = LED_PIN

#define TLV_RESET_RELEASE TLV_RESET_PORT->scr = TLV_RESET_PIN

#define I2C_SPEED 100000
#define I2C_INSTANCE I2C1
#define I2C_CLK CRM_I2C1_PERIPH_CLOCK
#define I2C_SCL_GPIO_CLK CRM_GPIOB_PERIPH_CLOCK
#define I2C_SDA_GPIO_CLK CRM_GPIOB_PERIPH_CLOCK
#define I2C_SCL_PIN GPIO_PINS_8
#define I2C_SCL_GPIO_PORT GPIOB
#define I2C_SDA_PIN GPIO_PINS_9
#define I2C_SDA_GPIO_PORT GPIOB
#define I2C_MUX I2C1_MUX

#define I2C_TIMEOUT 1000000

#define I2S_INSTANCE SPI1
#define I2S_CLK CRM_SPI1_PERIPH_CLOCK
#define I2S_MUX SPI1_MUX_11
#define I2S_WS_GPIO_CLK CRM_GPIOA_PERIPH_CLOCK
#define I2S_WS_PIN GPIO_PINS_15
#define I2S_WS_GPIO_PORT GPIOA
#define I2S_CK_GPIO_CLK CRM_GPIOB_PERIPH_CLOCK
#define I2S_CK_PIN GPIO_PINS_3
#define I2S_CK_GPIO_PORT GPIOB
#define I2S_SD_GPIO_CLK CRM_GPIOB_PERIPH_CLOCK
#define I2S_SD_PIN GPIO_PINS_5
#define I2S_SD_GPIO_PORT GPIOB
#define I2S_MCK_GPIO_CLK CRM_GPIOB_PERIPH_CLOCK
#define I2S_MCK_PIN GPIO_PINS_6
#define I2S_MCK_GPIO_PORT GPIOB

#define I2S_DMA_CLK CRM_DMA1_PERIPH_CLOCK
#define I2S_DMA_CHANNEL DMA1_CHANNEL3
#define I2S_DMA_IRQ DMA1_Channel3_IRQn
#define I2S_DMA_IRQ_HANDLER DMA1_Channel3_IRQHandler
#define I2S_DT_ADDRESS &SPI1->dt

void HALInit(audio_codec_type *param);

#endif
