#ifndef _BOARD_H
#define _BOARD_H

#ifndef NULL
#define NULL 0
#endif

#include "MCXN236.h"

#define SYSTICK_MULTIPLIER (DEFAULT_SYSTEM_CLOCK/1000000)

#define BOARD_LED_RED_GPIO GPIO4
#define BOARD_LED_RED_GPIO_PIN 18U
#define BOARD_LED_BLUE_GPIO GPIO4
#define BOARD_LED_BLUE_GPIO_PIN 17U
#define BOARD_LED_GREEN_GPIO GPIO4
#define BOARD_LED_GREEN_GPIO_PIN 19U

#define BOARD_SW2_GPIO GPIO0
#define BOARD_SW2_GPIO_PIN 20U
#define BOARD_SW3_GPIO GPIO0
#define BOARD_SW3_GPIO_PIN 6U

#define LED_GREEN_ON GPIO4->PCOR = (1 << BOARD_LED_GREEN_GPIO_PIN)
#define LED_GREEN_OFF GPIO4->PSOR = (1 << BOARD_LED_GREEN_GPIO_PIN)
#define LED_GREEN_TOGGLE GPIO4->PTOR = (1 << BOARD_LED_GREEN_GPIO_PIN)

#define LED_RED_ON GPIO4->PCOR = (1 << BOARD_LED_RED_GPIO_PIN)
#define LED_RED_OFF GPIO4->PSOR = (1 << BOARD_LED_RED_GPIO_PIN)
#define LED_RED_TOGGLE GPIO4->PTOR = (1 << BOARD_LED_RED_GPIO_PIN)

#define LED_BLUE_ON GPIO4->PCOR = (1 << BOARD_LED_BLUE_GPIO_PIN)
#define LED_BLUE_OFF GPIO4->PSOR = (1 << BOARD_LED_BLUE_GPIO_PIN)
#define LED_BLUE_TOGGLE GPIO4->PTOR = (1 << BOARD_LED_BLUE_GPIO_PIN)

void HalInit(void);

#endif
