#ifndef _MULTIMETER_ENUMS_H
#define _MULTIMETER_ENUMS_H

typedef enum
{
  CHANNEL_TYPE_NONE,
  CHANNEL_TYPE_VOLTAGE,
  CHANNEL_TYPE_CURRENT,
  CHANNEL_TYPE_RESISTANCE,
  CHANNEL_TYPE_TEMPERATURE,
  CHANNEL_TYPE_VDDA,
  CHANNEL_TYPE_CAPACITANCE,
  CHANNEL_TYPE_FREQUENCY,
  CHANNEL_TYPE_MAX = CHANNEL_TYPE_FREQUENCY
} MultimeterChannelType;

typedef enum
{
  CURRENT_LEVEL_LO,
  CURRENT_LEVEL_MID,
  CURRENT_LEVEL_HI,
  CURRENT_LEVEL_MAX = CURRENT_LEVEL_HI
} CurrentSourceLevel;

#endif
